package com.velopayments.api.model.payout;

/**
 *
 */
public enum ReasonType {

    UNKNOWN_REMOTE_ID,
    UNKNOWN_SOURCE_ACCOUNT,
    UNSUPPORTED_CURRENCY,
    PAYMENT_VALUE_TOO_HIGH,
    UNSUPPORTED_COUNTRY,
    UNSUPPORTED_CURRENCY_FOR_COUNTRY,
    PAYEE_NOT_ONBOARDED,
    COMPLIANCE_ISSUE,
    DUPLICATE_PAYOR_PAYMENT_ID,
    CURRENCY_MISMATCH,
    DECLINED_INVITE,
    PENDING_INVITE,
    BADLY_FORMED_DATA_ROW,
    REJECTED_BY_RAILS,
    MISSING_WU_CUSTOMER_ID,
    OTHER
}
